### ISSUE TITLE
how to run "npm install --arch=x64 --platform=linux sharp" before zip happen on Mac

### ISSUE THREAD

**Issue by PrimeObjects** [weixu365/serverless-scriptable-plugin#102]
In the .serverless/lambdaname.zip file it is always have node_modules/sharp/buidl/Release/sharp-darwin-x64.node
I know if I can run the following command it will enforce it to install the sharp-linux version. What is the right setting to run this before zip happens?
npm install --arch=x64 --platform=linux sharp

Thanks Lot

Cheers
Gary

**Comment by weixu365** [comment]
You could try the following settings to force install the linux version of sharp, but after that, your local dependencies won't work.

```
plugins:
  - serverless-scriptable-plugin

custom:
  scriptable:
    hooks:
      before:package:createDeploymentArtifacts: npm uninstall sharp && npm install --arch=x64 --platform=linux sharp
```

**In the projects I have worked with, I normally use docker to run serverless commands, so it would install the linux version by default.**
