### ISSUE TITLE
Better name for runcmd

### ISSUE THREAD

**Issue by bebbi** [weixu365/serverless-scriptable-plugin#79]
Hey, I missed that the `runcmd` string is exposed to users, sorry! See here:

```
custom:
  scriptable:
    hooks:
      before:migrate:runcmd: echo before migrating
      after:migrate:runcmd: echo after migrating
    commands:
      migrate: echo Running migration
```

Before there's too much uptake, how about if I change that to something cleaner? For example, how about a change for getting this:

```
custom:
  scriptable:
    hooks:
      before:command:migrate: echo before migrating
      after:command:migrate: echo after migrating
    commands:
      migrate: echo Running migration
```
